WIP
Signed-off-by: Andre Detsch <andre.detsch@foundries.io>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -58,56 +58,56 @@ jobs:
         run: make -f dev-flow.mk config build
 
 
-  garage-tools:
-    name: Build Garage Tools
-    runs-on: ubuntu-latest
-    container:
-      image: foundries/aklite-dev
-      env:
-        CXX: clang++
-        CC: clang
-        CCACHE_DIR: /__w/aktualizr-lite/aktualizr-lite/.ccache
+  # garage-tools:
+  #   name: Build Garage Tools
+  #   runs-on: ubuntu-latest
+  #   container:
+  #     image: foundries/aklite-dev
+  #     env:
+  #       CXX: clang++
+  #       CC: clang
+  #       CCACHE_DIR: /__w/aktualizr-lite/aktualizr-lite/.ccache
 
-    steps:
-      - uses: actions/checkout@v3
-      - run: git config --global --add safe.directory /__w/aktualizr-lite/aktualizr-lite
-      - run: git submodule update --init --recursive
-      - name: build garage tools
-        run: make -f dev-flow.mk garage-tools
-      - name: check garage tools
-        run: |
-          if [[ ! -f build-garage/aktualizr/src/sota_tools/garage-sign/bin/garage-sign ]]; then
-            echo "Failed to build garage-sign!"
-            exit 1
-          fi
-          if [[ ! -f build-garage/aktualizr/src/sota_tools/garage-push ]]; then
-            echo "Failed to build garage-push!"
-            exit 1
-          fi
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #     - run: git config --global --add safe.directory /__w/aktualizr-lite/aktualizr-lite
+  #     - run: git submodule update --init --recursive
+  #     - name: build garage tools
+  #       run: make -f dev-flow.mk garage-tools
+  #     - name: check garage tools
+  #       run: |
+  #         if [[ ! -f build-garage/aktualizr/src/sota_tools/garage-sign/bin/garage-sign ]]; then
+  #           echo "Failed to build garage-sign!"
+  #           exit 1
+  #         fi
+  #         if [[ ! -f build-garage/aktualizr/src/sota_tools/garage-push ]]; then
+  #           echo "Failed to build garage-push!"
+  #           exit 1
+  #         fi
 
-  test:
-    name: Tests
-    needs: fill-up-ccache
-    runs-on: ubuntu-latest
-    container:
-      image: foundries/aklite-dev
-      env:
-        CXX: clang++
-        CC: clang
-        CCACHE_DIR: /__w/aktualizr-lite/aktualizr-lite/.ccache
-    steps:
-      - uses: actions/checkout@v3
-      - run: git config --global --add safe.directory /__w/aktualizr-lite/aktualizr-lite
-      - run: git submodule update --init --recursive
-      - name: Restore ccache
-        uses: actions/cache@v4
-        with:
-          path: /__w/aktualizr-lite/aktualizr-lite/.ccache
-          key: e2e-ccache
-          restore-keys: |
-            e2e-ccache
-      - name: test
-        run: make -f dev-flow.mk config build test
+  # test:
+  #   name: Tests
+  #   needs: fill-up-ccache
+  #   runs-on: ubuntu-latest
+  #   container:
+  #     image: foundries/aklite-dev
+  #     env:
+  #       CXX: clang++
+  #       CC: clang
+  #       CCACHE_DIR: /__w/aktualizr-lite/aktualizr-lite/.ccache
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #     - run: git config --global --add safe.directory /__w/aktualizr-lite/aktualizr-lite
+  #     - run: git submodule update --init --recursive
+  #     - name: Restore ccache
+  #       uses: actions/cache@v4
+  #       with:
+  #         path: /__w/aktualizr-lite/aktualizr-lite/.ccache
+  #         key: e2e-ccache
+  #         restore-keys: |
+  #           e2e-ccache
+  #     - name: test
+  #       run: make -f dev-flow.mk config build test
 
   e2e-test-basic-online-single-step:
     name: Basic online, single step end-to-end tests
@@ -119,6 +119,7 @@ jobs:
 
     steps:
       - uses: actions/checkout@v4
+      - run: ls -l /
       - run: git config --global --add safe.directory /__w/aktualizr-lite/aktualizr-lite
       - run: git submodule update --init --recursive
       - run: mkdir -p /__w/aktualizr-lite/aktualizr-lite/.ccache
